@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Nov 10 17:35:35 +0900 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim ov7675_simulation_time_synth -key {Post-Synthesis:sim_1:Timing:ov7675_simulation} -tclbatch ov7675_simulation.tcl -protoinst "protoinst_files/ov7675_test.protoinst" -log simulate.log"
call xsim  ov7675_simulation_time_synth -key {Post-Synthesis:sim_1:Timing:ov7675_simulation} -tclbatch ov7675_simulation.tcl -protoinst "protoinst_files/ov7675_test.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
