# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ov7675_test.xdc

# Block Designs: bd/ov7675_test/ov7675_test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7675_test || ORIG_REF_NAME==ov7675_test} -quiet] -quiet

# IP: bd/ov7675_test/ip/ov7675_test_clk_wiz_0_0/ov7675_test_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7675_test_clk_wiz_0_0 || ORIG_REF_NAME==ov7675_test_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ov7675_test/ip/ov7675_test_VGA_test_0_0/ov7675_test_VGA_test_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7675_test_VGA_test_0_0 || ORIG_REF_NAME==ov7675_test_VGA_test_0_0} -quiet] -quiet

# IP: bd/ov7675_test/ip/ov7675_test_ov7675_ctrl_0_0/ov7675_test_ov7675_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7675_test_ov7675_ctrl_0_0 || ORIG_REF_NAME==ov7675_test_ov7675_ctrl_0_0} -quiet] -quiet

# IP: bd/ov7675_test/ip/ov7675_test_blk_mem_gen_0_1/ov7675_test_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7675_test_blk_mem_gen_0_1 || ORIG_REF_NAME==ov7675_test_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/ov7675_test/ip/ov7675_test_sccb_if_0_0/ov7675_test_sccb_if_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7675_test_sccb_if_0_0 || ORIG_REF_NAME==ov7675_test_sccb_if_0_0} -quiet] -quiet

# XDC: bd/ov7675_test/ov7675_test_ooc.xdc
