webtalk_init -webtalk_dir C:/Users/ikeno/Documents/VIVADO/OV7675_test/OV7675_test.sim/sim_1/behav/xsim/xsim.dir/ov7675_simulation_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov 10 16:49:13 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "33e160d1-55c3-4a1c-b082-1fbccf6ef1ba" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e47f50019af54d1d939bcc9c82350ca5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "5001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "33.50_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15608_KB" -context "xsim\\usage"
webtalk_transmit -clientid 84757095 -regid "" -xml C:/Users/ikeno/Documents/VIVADO/OV7675_test/OV7675_test.sim/sim_1/behav/xsim/xsim.dir/ov7675_simulation_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ikeno/Documents/VIVADO/OV7675_test/OV7675_test.sim/sim_1/behav/xsim/xsim.dir/ov7675_simulation_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ikeno/Documents/VIVADO/OV7675_test/OV7675_test.sim/sim_1/behav/xsim/xsim.dir/ov7675_simulation_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
